# Generated by Django 4.0 on 2022-01-02 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_uuid_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uuid',
            name='Platform',
            field=models.CharField(max_length=10),
        ),
    ]
