# Generated by Django 4.0 on 2022-01-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_uuid_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='FavoriteUUID',
            field=models.ManyToManyField(related_name='FavoriteID', to='api.UUID'),
        ),
    ]
