# Generated by Django 4.0 on 2022-01-02 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_verify_is_verified'),
        ('api', '0004_alter_favorite_favoriteuuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user', unique=True),
        ),
    ]
