# Generated by Django 4.0 on 2022-01-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_favorite_favoriteuuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='FavoriteUUID',
            field=models.ManyToManyField(related_name='FavoriteID', to='api.UUID'),
        ),
    ]
